## Introduction:
Predicting student performance plays a vital role in educational planning, enabling schools and educators to provide timely interventions and support. This project presents a machine learning approach using PyTorch to predict student outcomes based on real-time data collected from an actual academic institution.

The dataset includes features such as Date of Admission and % of Marks scored at Previous School, which are used to train a custom neural network model to predict the student's Roll Number. By working with authentic, real-world data, the model reflects practical challenges like inconsistent formatting, and non-numeric features — all of which are addressed through thorough preprocessing.Also some columns are drops for less importance.

This project demonstrates not only the application of deep learning techniques using PyTorch but also the practical process of turning raw educational data into meaningful predictive insights. The use of real-time data enhances the validity of the model and showcases its potential use in real academic environments.


Data is collected from "New Integrated Govt. School, Ramnagar-II"


In [1]:
# Import all the basic Libraries
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from torch.utils.data import Dataset, DataLoader


In [2]:
# Load the dataset
df=pd.read_csv("Student Strength(CSV).csv")

In [3]:
# Check the shape
df.shape

(37, 8)

In [4]:
# Check the information
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 37 entries, 0 to 36
Data columns (total 8 columns):
 #   Column                                Non-Null Count  Dtype  
---  ------                                --------------  -----  
 0   Sl No                                 37 non-null     int64  
 1   Roll No                               37 non-null     int64  
 2   Name of Student                       37 non-null     object 
 3   Date of Admission                     37 non-null     object 
 4   Sex                                   37 non-null     object 
 5   Religion                              37 non-null     object 
 6   Previous School Name                  37 non-null     object 
 7   % of Marks scored at Previous school  37 non-null     float64
dtypes: float64(1), int64(2), object(5)
memory usage: 2.4+ KB


In [5]:
# Check the columns
df.columns

Index(['Sl No', 'Roll No', 'Name of Student', 'Date of Admission', 'Sex',
       'Religion', 'Previous School Name',
       '% of Marks scored at Previous school'],
      dtype='object')

In [6]:
# Mean stander deviation printing
df.describe()

Sl No    Roll No  % of Marks scored at Previous school
count  37.000000  37.000000                             37.000000
mean   19.000000  21.972973                             61.884054
std    10.824355  12.063458                             23.711134
min     1.000000   1.000000                             33.000000
25%    10.000000  11.000000                             35.500000
50%    19.000000  23.000000                             61.000000
75%    28.000000  32.000000                             88.250000
max    37.000000  41.000000                             91.560000

In [7]:
#Check the null values
df.isnull().sum()

Sl No                                   0
Roll No                                 0
Name of Student                         0
Date of Admission                       0
Sex                                     0
Religion                                0
Previous School Name                    0
% of Marks scored at Previous school    0
dtype: int64

In [8]:
# Check the head
df.head()

Sl No  Roll No    Name of Student Date of Admission     Sex Religion  \
0      1        1  Moushali Guchhait        12-12-2024  Female    Hindu   
1      2        3          Sayan Das        12/13/2024    Male    Hindu   
2      3        4      Atanu Khutiya        12/14/2024    Male    Hindu   
3      4        5       Rekha Khatun        12/14/2024  Female   Muslim   
4      5        6      Anupam Bangal        12/16/2024    Male    Hindu   

            Previous School Name  % of Marks scored at Previous school  
0                  New Admission                                 91.56  
1  Dadanpatrabarh Primary School                                 91.25  
2                  New Admission                                 91.00  
3                  New Admission                                 90.75  
4                  New Admission                                 90.25

In [9]:
# Drop this columns for better model making
df.drop(columns=["Sl No", "Previous School Name", "Sex", "Religion"], inplace=True)


In [10]:
# Check the head after drop the columns
df.head()

Roll No    Name of Student Date of Admission  \
0        1  Moushali Guchhait        12-12-2024   
1        3          Sayan Das        12/13/2024   
2        4      Atanu Khutiya        12/14/2024   
3        5       Rekha Khatun        12/14/2024   
4        6      Anupam Bangal        12/16/2024   

   % of Marks scored at Previous school  
0                                 91.56  
1                                 91.25  
2                                 91.00  
3                                 90.75  
4                                 90.25

In [11]:
# Make the date of admission as dataframe
df["Date of Admission"] = pd.to_datetime(df["Date of Admission"], format="mixed", errors="coerce")
df["Date of Admission"] = df["Date of Admission"].dt.day
df.head()

Roll No    Name of Student  Date of Admission  \
0        1  Moushali Guchhait                 12   
1        3          Sayan Das                 13   
2        4      Atanu Khutiya                 14   
3        5       Rekha Khatun                 14   
4        6      Anupam Bangal                 16   

   % of Marks scored at Previous school  
0                                 91.56  
1                                 91.25  
2                                 91.00  
3                                 90.75  
4                                 90.25

In [12]:
# Deep Learning Model making by NN module
# split the dataset
features = df[["Date of Admission", "% of Marks scored at Previous school"]].values
targets = df["Roll No"].values

In [13]:
# Check the features
features

array([[12.  , 91.56],
       [13.  , 91.25],
       [14.  , 91.  ],
       [14.  , 90.75],
       [16.  , 90.25],
       [16.  , 90.15],
       [16.  , 89.  ],
       [17.  , 88.5 ],
       [17.  , 88.25],
       [17.  , 87.  ],
       [18.  , 84.  ],
       [18.  , 83.  ],
       [20.  , 80.  ],
       [21.  , 75.  ],
       [21.  , 70.  ],
       [21.  , 67.  ],
       [21.  , 63.  ],
       [21.  , 61.  ],
       [22.  , 58.  ],
       [22.  , 91.  ],
       [22.  , 57.25],
       [23.  , 56.  ],
       [23.  , 45.  ],
       [23.  , 44.5 ],
       [23.  , 44.25],
       [24.  , 40.  ],
       [24.  , 35.5 ],
       [24.  , 35.5 ],
       [24.  , 34.25],
       [24.  , 34.25],
       [24.  , 34.25],
       [26.  , 33.5 ],
       [26.  , 33.5 ],
       [28.  , 33.25],
       [28.  , 33.  ],
       [28.  , 33.  ],
       [28.  , 33.  ]])

In [14]:
# Check the targets
targets

array([ 1,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 14, 15, 18, 19, 20, 21,
       22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38,
       39, 40, 41])

In [15]:
# Standerization
scaler = StandardScaler()
features = scaler.fit_transform(features)

In [16]:
features

array([[-2.07582608,  1.26882538],
       [-1.84655574,  1.25557101],
       [-1.61728539,  1.24488201],
       [-1.61728539,  1.234193  ],
       [-1.15874471,  1.21281499],
       [-1.15874471,  1.20853939],
       [-1.15874471,  1.15936996],
       [-0.92947436,  1.13799195],
       [-0.92947436,  1.12730295],
       [-0.92947436,  1.07385792],
       [-0.70020402,  0.94558986],
       [-0.70020402,  0.90283383],
       [-0.24166333,  0.77456577],
       [-0.01239299,  0.56078566],
       [-0.01239299,  0.34700556],
       [-0.01239299,  0.21873749],
       [-0.01239299,  0.04771341],
       [-0.01239299, -0.03779863],
       [ 0.21687735, -0.1660667 ],
       [ 0.21687735,  1.24488201],
       [ 0.21687735, -0.19813371],
       [ 0.44614769, -0.25157874],
       [ 0.44614769, -0.72189498],
       [ 0.44614769, -0.74327299],
       [ 0.44614769, -0.75396199],
       [ 0.67541804, -0.93567508],
       [ 0.67541804, -1.12807718],
       [ 0.67541804, -1.12807718],
       [ 0.67541804,

In [17]:
# Define the Dataset for Dataset class and Dataloader
class StudentDataset(Dataset):
    def __init__(self, x, y):
        self.x = torch.tensor(x, dtype=torch.float32)
        self.y = torch.tensor(y, dtype=torch.float32)
    def __len__(self):
        return len(self.x)

    def __getitem__(self, idx):
        return self.x[idx], self.y[idx]

# Train-test split
x_train, x_test, y_train, y_test = train_test_split(features, targets,train_size=0.7,test_size=0.3, random_state=100)

train_dataset = StudentDataset(x_train, y_train)
test_dataset = StudentDataset(x_test, y_test)

train_loader = DataLoader(train_dataset, batch_size=4, shuffle=True)
test_loader = DataLoader(test_dataset, batch_size=4)


In [18]:
# nn modules uses
import torch.nn as nn
import torch.nn.functional as F

class CustomStudentNet(nn.Module):
    def __init__(self):
        super(CustomStudentNet, self).__init__()
        self.fc1 = nn.Linear(2, 16)
        self.fc2 = nn.Linear(16, 8)
        self.out = nn.Linear(8, 1)  #(2 values) → fc1 → (16) → fc2 → (8)->out → (1 final prediction)

    def forward(self, x):
        x = F.relu(self.fc1(x))
        x = F.relu(self.fc2(x))
        return self.out(x)


In [19]:
# Train the model
model = CustomStudentNet()
criterion = nn.MSELoss()
optimizer = torch.optim.SGD(model.parameters(), lr=0.01)

for epoch in range(50):
    model.train()
    total_loss = 0
    for batch_x, batch_y in train_loader:
        optimizer.zero_grad()
        outputs = model(batch_x).squeeze()
        loss = criterion(outputs, batch_y)
        loss.backward()
        optimizer.step()
        total_loss += loss.item()
    print(f"Epoch {epoch+1}, Loss: {total_loss:.2f}")


/usr/local/lib/python3.11/dist-packages/torch/nn/modules/loss.py:610: UserWarning: Using a target size (torch.Size([1])) that is different to the input size (torch.Size([])). This will likely lead to incorrect results due to broadcasting. Please ensure they have the same size.
  return F.mse_loss(input, target, reduction=self.reduction)


Epoch 1, Loss: 3348.04
Epoch 2, Loss: 1849.22
Epoch 3, Loss: 2653.65
Epoch 4, Loss: 1309.76
Epoch 5, Loss: 511.60
Epoch 6, Loss: 1238.57
Epoch 7, Loss: 253.67
Epoch 8, Loss: 110.42
Epoch 9, Loss: 80.11
Epoch 10, Loss: 107.19
Epoch 11, Loss: 449.65
Epoch 12, Loss: 69.90
Epoch 13, Loss: 56.56
Epoch 14, Loss: 45.95
Epoch 15, Loss: 32.45
Epoch 16, Loss: 85.80
Epoch 17, Loss: 42.92
Epoch 18, Loss: 51.77
Epoch 19, Loss: 169.60
Epoch 20, Loss: 52.52
Epoch 21, Loss: 45.31
Epoch 22, Loss: 73.13
Epoch 23, Loss: 76.92
Epoch 24, Loss: 72.48
Epoch 25, Loss: 49.30
Epoch 26, Loss: 35.13
Epoch 27, Loss: 155.55
Epoch 28, Loss: 113.12
Epoch 29, Loss: 104.33
Epoch 30, Loss: 46.76
Epoch 31, Loss: 38.02
Epoch 32, Loss: 30.12
Epoch 33, Loss: 33.99
Epoch 34, Loss: 54.56
Epoch 35, Loss: 100.27
Epoch 36, Loss: 40.37
Epoch 37, Loss: 65.11
Epoch 38, Loss: 32.83
Epoch 39, Loss: 108.88
Epoch 40, Loss: 44.45
Epoch 41, Loss: 43.03
Epoch 42, Loss: 27.43
Epoch 43, Loss: 56.91
Epoch 44, Loss: 163.11
Epoch 45, Loss: 48.

In [20]:
# Evaluate
import math
model.eval()
with torch.no_grad():
    total_loss = 0
    for batch_x, batch_y in test_loader:
        preds = model(batch_x).squeeze()
        loss = criterion(preds, batch_y)
        total_loss += loss.item()

avg_loss = total_loss / len(test_loader)
rmse = math.sqrt(avg_loss)

print(f"Test Loss: {total_loss:.2f}")
print(f"Average MSE per Batch: {avg_loss:.4f}")
print(f"Root Mean Squared Error (RMSE): {rmse:.2f}")

Test Loss: 37.68
Average MSE per Batch: 12.5603
Root Mean Squared Error (RMSE): 3.54


In [21]:
### Checking With new Data
# Example unseen data: date and marks
new_df = pd.DataFrame({
    "Date of Admission": ["2025-01-16"],
    "% of Marks scored at Previous school": [94.5]
})

# Convert into date only
new_df["Date of Admission"] = pd.to_datetime(new_df["Date of Admission"])
new_df["Date of Admission"] = new_df["Date of Admission"].dt.day

# Select same columns and scale
x_new = new_df[["Date of Admission", "% of Marks scored at Previous school"]].values
x_new_scaled = scaler.transform(x_new)

# Convert to tensor
x_new_tensor = torch.tensor(x_new_scaled, dtype=torch.float32)


In [22]:
model.eval()

with torch.no_grad():
    prediction = model(x_new_tensor)
    result = prediction.item()
    result= torch.tensor(result,dtype=torch.float32)
    result=result.ceil_()

print(f"Predicted Output: {result}")


Predicted Output: 9.0


## Conclusion:
In this project, we developed a neural network using PyTorch to predict student outcomes based on features such as admission date and previous academic performance. After preprocessing the data—including feature selection, scaling, and conversion to tensors—we trained a custom feedforward neural network using the Stochastic Gradient Descent (SGD) optimizer and Mean Squared Error (MSE) loss function.

The model architecture included multiple fully connected layers with ReLU activation, enabling it to capture non-linear relationships between the inputs and target (Roll No). After training, we evaluated the model on unseen data, calculated the average loss, and interpreted performance using Root Mean Squared Error (RMSE) for better clarity.

While the model achieved a functional level of accuracy, the loss values indicate that prediction performance could be further improved. This can be addressed by incorporating more relevant features (e.g., attendance, demographics), tuning hyperparameters, or experimenting with more advanced architectures.